version: '3.3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=INFO
      - FEATURE_BANK_PATH=data/feature_bank.csv
    volumes:
      - ./data:/app/data:ro
      - ./app.db:/app/app.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3 