[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[service]]
name = "transient-recommender"

[service.environment]
LOG_LEVEL = "INFO"
FEATURE_BANK_PATH = "data/feature_bank.csv"
PORT = "8080"

[service.source]
repo = "your-github-username/transient-recommender"
branch = "main"

[service.networking]
customDomain = "transientrecommender.org" 