"""Add classifier security and approval models

Revision ID: 0ebd02854468
Revises: c19f3481c3e2
Create Date: 2025-06-03 14:52:22.855943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebd02854468'
down_revision: Union[str, None] = 'c19f3481c3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ztfid', sa.String(), nullable=True),
    sa.Column('science_case', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classifier_name', sa.String(), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ztfid', 'science_case', 'classifier_name', name='unique_pending_vote')
    )
    op.create_index(op.f('ix_pending_votes_id'), 'pending_votes', ['id'], unique=False)
    op.create_index(op.f('ix_pending_votes_science_case'), 'pending_votes', ['science_case'], unique=False)
    op.create_index(op.f('ix_pending_votes_ztfid'), 'pending_votes', ['ztfid'], unique=False)
    op.create_table('classifier_approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classifier_name', sa.String(), nullable=True),
    sa.Column('science_case', sa.String(), nullable=True),
    sa.Column('python_code', sa.String(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('requesting_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('security_validated', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifier_approval_requests_classifier_name'), 'classifier_approval_requests', ['classifier_name'], unique=False)
    op.create_index(op.f('ix_classifier_approval_requests_code_hash'), 'classifier_approval_requests', ['code_hash'], unique=True)
    op.create_index(op.f('ix_classifier_approval_requests_id'), 'classifier_approval_requests', ['id'], unique=False)
    op.create_index(op.f('ix_classifier_approval_requests_science_case'), 'classifier_approval_requests', ['science_case'], unique=False)
    op.create_table('security_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('classifier_name', sa.String(), nullable=True),
    sa.Column('ztfid', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_logs_classifier_name'), 'security_audit_logs', ['classifier_name'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_type'), 'security_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_id'), 'security_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_timestamp'), 'security_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_ztfid'), 'security_audit_logs', ['ztfid'], unique=False)
    op.create_table('custom_classifier_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ztfid', sa.String(), nullable=True),
    sa.Column('classifier_name', sa.String(), nullable=True),
    sa.Column('science_case', sa.String(), nullable=True),
    sa.Column('classification_label', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('approval_request_id', sa.Integer(), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('feature_extraction_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_request_id'], ['classifier_approval_requests.id'], ),
    sa.ForeignKeyConstraint(['feature_extraction_run_id'], ['feature_extraction_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ztfid', 'classifier_name', 'science_case', name='unique_classifier_result')
    )
    op.create_index(op.f('ix_custom_classifier_results_classifier_name'), 'custom_classifier_results', ['classifier_name'], unique=False)
    op.create_index(op.f('ix_custom_classifier_results_id'), 'custom_classifier_results', ['id'], unique=False)
    op.create_index(op.f('ix_custom_classifier_results_science_case'), 'custom_classifier_results', ['science_case'], unique=False)
    op.create_index(op.f('ix_custom_classifier_results_ztfid'), 'custom_classifier_results', ['ztfid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_classifier_results_ztfid'), table_name='custom_classifier_results')
    op.drop_index(op.f('ix_custom_classifier_results_science_case'), table_name='custom_classifier_results')
    op.drop_index(op.f('ix_custom_classifier_results_id'), table_name='custom_classifier_results')
    op.drop_index(op.f('ix_custom_classifier_results_classifier_name'), table_name='custom_classifier_results')
    op.drop_table('custom_classifier_results')
    op.drop_index(op.f('ix_security_audit_logs_ztfid'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_timestamp'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_type'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_classifier_name'), table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_index(op.f('ix_classifier_approval_requests_science_case'), table_name='classifier_approval_requests')
    op.drop_index(op.f('ix_classifier_approval_requests_id'), table_name='classifier_approval_requests')
    op.drop_index(op.f('ix_classifier_approval_requests_code_hash'), table_name='classifier_approval_requests')
    op.drop_index(op.f('ix_classifier_approval_requests_classifier_name'), table_name='classifier_approval_requests')
    op.drop_table('classifier_approval_requests')
    op.drop_index(op.f('ix_pending_votes_ztfid'), table_name='pending_votes')
    op.drop_index(op.f('ix_pending_votes_science_case'), table_name='pending_votes')
    op.drop_index(op.f('ix_pending_votes_id'), table_name='pending_votes')
    op.drop_table('pending_votes')
    # ### end Alembic commands ###
