"""add_last_detection_mjd_to_feature_bank

Revision ID: 785eeb1df998
Revises: 0ebd02854468
Create Date: 2025-07-02 05:22:16.996976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785eeb1df998'
down_revision: Union[str, None] = '0ebd02854468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_bank', sa.Column('last_detection_mjd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_bank', 'last_detection_mjd')
    # ### end Alembic commands ###
