"""Add comments table for individual comment management

Revision ID: 8e4fe9dfca3c
Revises: 27267cac8876
Create Date: 2025-05-28 11:58:37.772646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4fe9dfca3c'
down_revision: Union[str, None] = '27267cac8876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
