"""Add anomaly detection tables

Revision ID: c19f3481c3e2
Revises: 5c7cbaa77480
Create Date: 2025-06-03 13:23:59.902750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19f3481c3e2'
down_revision: Union[str, None] = '5c7cbaa77480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_detection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ztfid', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('mjd_anom', sa.JSON(), nullable=True),
    sa.Column('anom_scores', sa.JSON(), nullable=True),
    sa.Column('norm_scores', sa.JSON(), nullable=True),
    sa.Column('detection_threshold', sa.Float(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=True),
    sa.Column('feature_extraction_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feature_extraction_run_id'], ['feature_extraction_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ztfid', name='unique_anomaly_result')
    )
    op.create_index(op.f('ix_anomaly_detection_results_id'), 'anomaly_detection_results', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_detection_results_ztfid'), 'anomaly_detection_results', ['ztfid'], unique=False)
    op.create_table('anomaly_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_run_id', sa.Integer(), nullable=True),
    sa.Column('objects_detected', sa.Integer(), nullable=True),
    sa.Column('ztfids_detected', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detection_run_id'], ['feature_extraction_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_notifications_id'), 'anomaly_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_notifications_id'), table_name='anomaly_notifications')
    op.drop_table('anomaly_notifications')
    op.drop_index(op.f('ix_anomaly_detection_results_ztfid'), table_name='anomaly_detection_results')
    op.drop_index(op.f('ix_anomaly_detection_results_id'), table_name='anomaly_detection_results')
    op.drop_table('anomaly_detection_results')
    # ### end Alembic commands ###
