"""Add processed_features column to feature_bank

Revision ID: eefed8fcdccd
Revises: 8e4fe9dfca3c
Create Date: 2025-05-28 22:07:44.913517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefed8fcdccd'
down_revision: Union[str, None] = '8e4fe9dfca3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_bank', sa.Column('processed_features', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_bank', 'processed_features')
    # ### end Alembic commands ###
