name: CI - Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y librdkafka-dev
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test imports and basic functionality
      run: |
        python -c "import app; print('App imports successfully')"
        python -c "from app.recommender import WebRecommender; print('Recommender imports successfully')"
        
    - name: Test database models
      run: |
        python -c "from app.models import User, Vote, Tag, Note; print('Models import successfully')"

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t transient-recommender .
        echo "Docker image built successfully"
        
    - name: Test Docker container startup
      run: |
        docker run -d --name test-container -p 5000:5000 transient-recommender
        sleep 30
        docker logs test-container
        docker stop test-container
        echo "Docker container test completed" 